name: jbig2
description: Pure dart jbig2
version: 1.0.0
homepage: https://github.com/insinfo/jbig2
publish_to: none

environment:
  sdk: ^3.6.0
  
dependencies:
  logging: ^1.3.0

 
dev_dependencies:  
  crypto: ^3.0.7
  test: ^1.26.3

  

 

